# Generated by Django 6.0.6 on 2026-06-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0033_admissionstudent_gender_applying_class_admit_semester"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admissionstudent",
            name="admission_policy_agreement",
            field=models.BooleanField(
                default=False,
                verbose_name="I have read and agree to the admission policy, fee structure, and rules of the institution.",
            ),
        ),
    ]
