# Generated by Django 6.0.6 on 2026-06-19 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0003_seed_bd_subjects_school_madrasah"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="curriculumsubject",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="curriculum",
            name="board",
        ),
        migrations.RemoveField(
            model_name="curriculum",
            name="institute_type",
        ),
        migrations.RemoveField(
            model_name="curriculumlevel",
            name="semester_number",
        ),
        migrations.AddField(
            model_name="curriculumlevel",
            name="stage",
            field=models.CharField(
                choices=[
                    ("primary", "Primary (Grade 1-6)"),
                    ("secondary", "Secondary (Form 1-5)"),
                ],
                default="primary",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="curriculum",
            name="code",
            field=models.CharField(
                blank=True, help_text="Short code for display.", max_length=40
            ),
        ),
        migrations.AlterField(
            model_name="curriculumlevel",
            name="level_number",
            field=models.PositiveSmallIntegerField(
                help_text="Numeric level (1-6 for Primary, 1-5 for Secondary)."
            ),
        ),
        migrations.AlterField(
            model_name="curriculumlevel",
            name="name",
            field=models.CharField(
                help_text='Display name (e.g. "Grade 1", "Form 1").', max_length=80
            ),
        ),
        migrations.AlterField(
            model_name="curriculumlevel",
            name="streams_applicable",
            field=models.BooleanField(
                default=False, help_text="True if subjects defined per stream."
            ),
        ),
        migrations.AlterField(
            model_name="curriculumsubject",
            name="is_compulsory",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="curriculumsubject",
            name="stream",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="curriculum_subjects",
                to="curriculum.stream",
            ),
        ),
        migrations.AlterField(
            model_name="subjecttemplate",
            name="code",
            field=models.CharField(
                help_text="Unique code (e.g. MATH, ENG).", max_length=30, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="subjecttemplate",
            name="is_elective",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="curriculumsubject",
            constraint=models.UniqueConstraint(
                fields=("curriculum", "level", "stream", "subject_template"),
                name="unique_curriculum_subject",
            ),
        ),
    ]
